import { ProductSpec } from '../types/product';

export const DEFAULT_PRODUCT_SPECS: ProductSpec[] = [
  {
    id: 'spec-envelope',
    name: 'Custom Envelope (C5)',
    qty: 1,
    trimW: 229,
    trimH: 162,
    bleed: 3,
    safe: 5,
    faces: [
      {
        id: 'face-envelope',
        label: 'Envelope Front',
        artBrief: 'An ornate engraved frame running along the outer perimeter, framing the central address zone with refined linework and corner flourishes.',
        clearZone: { x: 70, y: 50, w: 140, h: 90 },
        logoSlot: { x: 20, y: 20, w: 45, h: 25 },
        textFields: [
          {
            id: 'env-sender-title',
            label: 'Sender Heading',
            role: 'heading',
            x: 20,
            y: 50,
            w: 45,
            h: 12,
            sizePt: 9,
            align: 'left',
            leading: 11,
            placeholder: 'COACHING ACADEMY',
            maxChars: 30,
            color: 'primary',
          },
          {
            id: 'env-sender-details',
            label: 'Sender Address',
            role: 'body',
            x: 20,
            y: 64,
            w: 45,
            h: 30,
            sizePt: 7.5,
            align: 'left',
            leading: 9.5,
            multiline: true,
            placeholder: 'Executive Mentorship Suite\n100 Knowledge Boulevard\nwww.example.com',
            maxChars: 90,
            color: 'muted',
          },
          {
            id: 'env-recipient',
            label: 'Recipient Block',
            role: 'body',
            x: 80,
            y: 75,
            w: 120,
            h: 40,
            sizePt: 12,
            align: 'left',
            leading: 16,
            multiline: true,
            placeholder: 'Prepared exclusively for:\n[Client Full Name]\nConfidential Delivery',
            maxChars: 100,
            color: 'ink',
          },
        ],
      },
    ],
  },
  {
    id: 'spec-monthly-tracker',
    name: 'Monthly Tracker',
    qty: 4,
    trimW: 105,
    trimH: 148,
    bleed: 3,
    safe: 5,
    copyLabels: ['Month One', 'Month Two', 'Month Three', 'Month Four'],
    faces: [
      {
        id: 'face-monthly-tracker',
        label: 'Monthly Tracker Card',
        artBrief: 'A subtle hairline border along the very perimeter, leaving the interior open and clear for grid ruling.',
        clearZone: { x: 10, y: 15, w: 85, h: 120 },
        logoSlot: { x: 37.5, y: 12, w: 30, h: 12 },
        textFields: [
          {
            id: 'tracker-title',
            label: 'Tracker Title',
            role: 'heading',
            x: 12,
            y: 26,
            w: 81,
            h: 12,
            sizePt: 14,
            align: 'center',
            leading: 16,
            placeholder: 'Month one',
            copyPlaceholders: ['Month one', 'Month two', 'Month three', 'Month four'],
            maxChars: 24,
            color: 'ink',
          },
          {
            id: 'tracker-subtitle',
            label: 'Tracker Subtitle',
            role: 'body',
            x: 12,
            y: 38,
            w: 81,
            h: 8,
            sizePt: 7.5,
            align: 'center',
            leading: 9,
            placeholder: 'HABIT & PERFORMANCE BENCHMARK',
            maxChars: 40,
            color: 'primary',
          },
          {
            id: 'tracker-notes-heading',
            label: 'Notes Heading',
            role: 'heading',
            x: 14,
            y: 116,
            w: 77,
            h: 6,
            sizePt: 7,
            align: 'left',
            leading: 8,
            placeholder: 'KEY BREAKTHROUGHS & WINS',
            maxChars: 35,
            color: 'muted',
          },
        ],
      },
    ],
  },
  {
    id: 'spec-goal-card',
    name: 'Goal Card (2-Sided)',
    qty: 1,
    trimW: 105,
    trimH: 148,
    bleed: 3,
    safe: 5,
    faces: [
      {
        id: 'face-goal-front',
        label: 'Goal Card (Front)',
        artBrief: 'A structured geometric frame running along the outer edges with decorative corner notches, framing an open interior panel.',
        clearZone: { x: 12, y: 22, w: 81, h: 104 },
        logoSlot: { x: 37.5, y: 14, w: 30, h: 12 },
        textFields: [
          {
            id: 'goal-front-title',
            label: 'Vision Heading',
            role: 'heading',
            x: 14,
            y: 28,
            w: 77,
            h: 12,
            sizePt: 13,
            align: 'center',
            leading: 15,
            placeholder: 'MY 90-DAY NORTH STAR',
            maxChars: 30,
            color: 'ink',
          },
          {
            id: 'goal-front-prompt1',
            label: 'Primary Goal Prompt',
            role: 'heading',
            x: 14,
            y: 44,
            w: 77,
            h: 6,
            sizePt: 8,
            align: 'left',
            leading: 9.5,
            placeholder: '1. THE NON-NEGOTIABLE OUTCOME',
            maxChars: 40,
            color: 'primary',
          },
          {
            id: 'goal-front-prompt2',
            label: 'Secondary Goal Prompt',
            role: 'heading',
            x: 14,
            y: 74,
            w: 77,
            h: 6,
            sizePt: 8,
            align: 'left',
            leading: 9.5,
            placeholder: '2. THE CORE METRIC OF SUCCESS',
            maxChars: 40,
            color: 'primary',
          },
          {
            id: 'goal-front-prompt3',
            label: 'Identity Anchor',
            role: 'heading',
            x: 14,
            y: 104,
            w: 77,
            h: 6,
            sizePt: 8,
            align: 'left',
            leading: 9.5,
            placeholder: '3. WHO I BECOME IN THIS SPRINT',
            maxChars: 40,
            color: 'primary',
          },
        ],
      },
      {
        id: 'face-goal-back',
        label: 'Goal Card (Back)',
        artBrief: 'A delicate double-ruled border tracing the outer margins, keeping the entire centre pale and spacious for handwritten notes.',
        clearZone: { x: 12, y: 18, w: 81, h: 112 },
        textFields: [
          {
            id: 'goal-back-heading',
            label: 'Milestones Title',
            role: 'heading',
            x: 14,
            y: 20,
            w: 77,
            h: 10,
            sizePt: 11,
            align: 'center',
            leading: 13,
            placeholder: 'MILESTONES & CELEBRATIONS',
            maxChars: 32,
            color: 'ink',
          },
          {
            id: 'goal-back-body',
            label: 'Commitment Text',
            role: 'body',
            x: 14,
            y: 34,
            w: 77,
            h: 30,
            sizePt: 8,
            align: 'center',
            leading: 11,
            multiline: true,
            placeholder: 'When clarity meets disciplined daily execution, transformation becomes inevitable.',
            maxChars: 120,
            color: 'muted',
          },
          {
            id: 'goal-back-reward-label',
            label: 'Reward Prompt',
            role: 'heading',
            x: 14,
            y: 105,
            w: 77,
            h: 6,
            sizePt: 8,
            align: 'center',
            leading: 9.5,
            placeholder: 'MY REWARD UPON COMPLETION',
            maxChars: 35,
            color: 'primary',
          },
        ],
      },
    ],
  },
  {
    id: 'spec-sticker-sheet',
    name: 'Sticker Sheet (A5)',
    qty: 1,
    trimW: 148,
    trimH: 210,
    bleed: 3,
    safe: 5,
    faces: [
      {
        id: 'face-sticker-sheet',
        label: 'Sticker Sheet',
        artBrief: 'A decorative sheet of elegant stationery badges, circular seals, banners, and motivational crests spaced across the canvas.',
        allowLettering: true,
        textFields: [], // sticker sheet graphics contain lettering drawn by model
      },
    ],
  },
  {
    id: 'spec-thank-you',
    name: 'Thank You Letter (A5)',
    qty: 1,
    trimW: 148,
    trimH: 210,
    bleed: 3,
    safe: 5,
    faces: [
      {
        id: 'face-thank-you',
        label: 'Thank You Letter',
        artBrief: 'An elegant letterhead border along the four outer margins with subtle corner motifs, leaving the wide letter interior immaculate and pale.',
        clearZone: { x: 16, y: 38, w: 116, h: 148 },
        logoSlot: { x: 54, y: 16, w: 40, h: 18 },
        textFields: [
          {
            id: 'letter-salutation',
            label: 'Salutation',
            role: 'heading',
            x: 18,
            y: 42,
            w: 112,
            h: 12,
            sizePt: 13,
            align: 'left',
            leading: 15,
            placeholder: 'Welcome to the Program,',
            maxChars: 35,
            color: 'ink',
          },
          {
            id: 'letter-body',
            label: 'Letter Body',
            role: 'body',
            x: 18,
            y: 58,
            w: 112,
            h: 90,
            sizePt: 9.5,
            align: 'left',
            leading: 14.5,
            multiline: true,
            placeholder: 'It is a privilege to welcome you into this intensive coaching container. You are here because you have chosen mastery, deliberate action, and uncompromising standards.\n\nKeep these physical tools on your desk as daily anchors. Trust the process, engage with every session, and honor the commitments you make to yourself.\n\nHere is to your breakthrough sprint.',
            maxChars: 450,
            color: 'ink',
          },
          {
            id: 'letter-signoff',
            label: 'Sign-off',
            role: 'body',
            x: 18,
            y: 156,
            w: 60,
            h: 8,
            sizePt: 9.5,
            align: 'left',
            leading: 12,
            placeholder: 'With dedication and respect,',
            maxChars: 40,
            color: 'muted',
          },
          {
            id: 'letter-coach-name',
            label: 'Coach Name',
            role: 'heading',
            x: 18,
            y: 166,
            w: 70,
            h: 10,
            sizePt: 11,
            align: 'left',
            leading: 13,
            placeholder: 'Your Coach & Mentor',
            maxChars: 35,
            color: 'primary',
          },
          {
            id: 'letter-accent',
            label: 'Decorative Accent Phrase',
            role: 'heading',
            x: 18,
            y: 184,
            w: 112,
            h: 10,
            sizePt: 9,
            align: 'center',
            leading: 11,
            placeholder: '',
            maxChars: 42,
            color: 'secondary',
          },
        ],
      },
    ],
  },
  {
    id: 'spec-affirmation-card',
    name: 'Affirmation Card',
    qty: 1,
    trimW: 105,
    trimH: 148,
    bleed: 3,
    safe: 5,
    faces: [
      {
        id: 'face-affirmation',
        label: 'Affirmation Card',
        artBrief: 'A refined ornamental cartouche framing the centre, with flourishes along the edges and a peaceful open central field.',
        clearZone: { x: 14, y: 32, w: 77, h: 84 },
        logoSlot: { x: 37.5, y: 15, w: 30, h: 12 },
        textFields: [
          {
            id: 'aff-top-label',
            label: 'Category Label',
            role: 'heading',
            x: 14,
            y: 38,
            w: 77,
            h: 8,
            sizePt: 8,
            align: 'center',
            leading: 10,
            placeholder: 'DAILY FOCUS & CONVICTION',
            maxChars: 30,
            color: 'primary',
          },
          {
            id: 'aff-main-quote',
            label: 'Core Affirmation',
            role: 'heading',
            x: 14,
            y: 52,
            w: 77,
            h: 40,
            sizePt: 13.5,
            align: 'center',
            leading: 17,
            multiline: true,
            placeholder: 'My discipline creates my freedom. My daily habits shape my ultimate legacy.',
            maxChars: 120,
            color: 'ink',
          },
          {
            id: 'aff-footer',
            label: 'Footer Note',
            role: 'body',
            x: 14,
            y: 100,
            w: 77,
            h: 8,
            sizePt: 7.5,
            align: 'center',
            leading: 9,
            placeholder: 'Read aloud upon morning review',
            maxChars: 40,
            color: 'muted',
          },
        ],
      },
    ],
  },
  {
    id: 'spec-referral-coupon',
    name: 'Referral Coupon',
    qty: 4,
    trimW: 85,
    trimH: 55,
    bleed: 3,
    safe: 5,
    copyLabels: ['Referral 01', 'Referral 02', 'Referral 03', 'Referral 04'],
    faces: [
      {
        id: 'face-referral-coupon',
        label: 'Referral Coupon',
        artBrief: 'A fine security-style border tracing the very edge of the card, leaving maximum open area for crisp typography.',
        clearZone: { x: 8, y: 7, w: 69, h: 41 },
        logoSlot: { x: 10, y: 8, w: 22, h: 10 },
        textFields: [
          {
            id: 'ref-heading',
            label: 'Header',
            role: 'heading',
            x: 34,
            y: 9,
            w: 43,
            h: 7,
            sizePt: 8,
            align: 'right',
            leading: 9,
            placeholder: 'EXCLUSIVE INVITATION',
            maxChars: 25,
            color: 'primary',
          },
          {
            id: 'ref-benefit',
            label: 'Offer Benefit',
            role: 'heading',
            x: 10,
            y: 20,
            w: 65,
            h: 9,
            sizePt: 10,
            align: 'left',
            leading: 12,
            placeholder: 'Complimentary Strategic Diagnostic',
            maxChars: 40,
            color: 'ink',
          },
          {
            id: 'ref-code',
            label: 'Voucher Code',
            role: 'heading',
            x: 10,
            y: 31,
            w: 32,
            h: 7,
            sizePt: 9,
            align: 'left',
            leading: 10,
            placeholder: 'REFER-01',
            copyPlaceholders: ['REFER-01', 'REFER-02', 'REFER-03', 'REFER-04'],
            maxChars: 15,
            color: 'primary',
          },
          {
            id: 'ref-terms',
            label: 'Terms & Conditions',
            role: 'body',
            x: 10,
            y: 40,
            w: 65,
            h: 7,
            sizePt: 6.5,
            align: 'left',
            leading: 7.5,
            placeholder: 'Single-use pass for an executive referral. Valued at Rs 15,000.',
            maxChars: 75,
            color: 'muted',
          },
        ],
      },
    ],
  },
  {
    id: 'spec-upgrade-coupon',
    name: 'Upgrade Coupon',
    qty: 1,
    trimW: 85,
    trimH: 55,
    bleed: 3,
    safe: 5,
    faces: [
      {
        id: 'face-upgrade-coupon',
        label: 'Upgrade Coupon',
        artBrief: 'A sleek stepped art deco border along the perimeter, maintaining an open and pale central panel.',
        clearZone: { x: 8, y: 7, w: 69, h: 41 },
        logoSlot: { x: 10, y: 8, w: 22, h: 10 },
        textFields: [
          {
            id: 'upg-heading',
            label: 'Header',
            role: 'heading',
            x: 34,
            y: 9,
            w: 43,
            h: 7,
            sizePt: 8,
            align: 'right',
            leading: 9,
            placeholder: 'ALUMNI PRIVILEGE',
            maxChars: 25,
            color: 'primary',
          },
          {
            id: 'upg-benefit',
            label: 'Benefit Title',
            role: 'heading',
            x: 10,
            y: 20,
            w: 65,
            h: 9,
            sizePt: 10.5,
            align: 'left',
            leading: 12,
            placeholder: 'Rs 25,000 Mastermind Credit',
            maxChars: 35,
            color: 'ink',
          },
          {
            id: 'upg-code',
            label: 'Privilege Code',
            role: 'heading',
            x: 10,
            y: 31,
            w: 32,
            h: 7,
            sizePt: 9,
            align: 'left',
            leading: 10,
            placeholder: 'UPGRADE-VIP',
            maxChars: 15,
            color: 'primary',
          },
          {
            id: 'upg-terms',
            label: 'Terms & Conditions',
            role: 'body',
            x: 10,
            y: 40,
            w: 65,
            h: 7,
            sizePt: 6.5,
            align: 'left',
            leading: 7.5,
            placeholder: 'Applicable toward advanced private advisory extension upon graduation.',
            maxChars: 80,
            color: 'muted',
          },
        ],
      },
    ],
  },
];

export function getAllFaces(): Array<{ spec: ProductSpec; face: import('../types/product').Face }> {
  const result: Array<{ spec: ProductSpec; face: import('../types/product').Face }> = [];
  for (const spec of DEFAULT_PRODUCT_SPECS) {
    for (const face of spec.faces) {
      result.push({ spec, face });
    }
  }
  return result;
}

export function getTotalPrintedPagesCount(): number {
  return DEFAULT_PRODUCT_SPECS.reduce((acc, spec) => acc + (spec.qty * spec.faces.length), 0);
}
